name: Bug Report
description: Báo cáo lỗi hệ thống
title: "[BUG] "
labels:
  - bug

body:
  - type: textarea
    id: description
    attributes:
      label: Mô tả lỗi
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Các bước tái hiện
      placeholder: |
        1. Truy cập...
        2. Thực hiện...
        3. Quan sát...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Kết quả mong đợi
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Kết quả thực tế
    validations:
      required: true